### ISSUE TITLE
How to create exact route in this case?

### ISSUE THREAD

**Issue by jorvenloh** [sakibshaik/express-clean-routes#10]
const paths = [
    {
        'path' : '/transactions/estimate',
        'method' : 'get',
        'middlewares' : [],
        'handlers' : getEstimateFee
    },
    {
        'path' : '/transactions/:hashId',
        'method' : 'get',
        'middlewares' : [],
        'handlers' : getTransaction
    }
]

**Comment by sakibshaik** [comment]
is it about the hashId (dynamic routes)?

**Comment by sakibshaik** [comment]
please check the readme for dynamic routes

**Comment by jorvenloh** [comment]
> is it about the hashId (dynamic routes)?

Yes that dynamic route is working fine, but what if I want another another route which meant to be same pattern with the dynamic route to works with other handler? Please check the path constant given above. this path /transactions/estimate is not working with getEstimateFee handler is the issue
